#!/usr/bin/env bash
# Configures host file to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/g' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
