#!/usr/bin/env bash
# Configures host file to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts
if ! grep -q "127.0.0.2 localhost" /etc/hosts; then
    echo "127.0.0.2 localhost" >> /etc/hosts
fi
echo "8.8.8.8 facebook.com" >> /etc/hosts
