#!/usr/bin/env bash
# Configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in hosts file

sed 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts > /tmp/hosts.tmp && cat /tmp/hosts.tmp > /etc/hosts
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" >> /etc/hosts
